# IBM Data Science Course Capstone Project


### 1. Team clustering 
### 1.1 Players stats and bio info

Stats: 

Bio info:

### 1.2 Team stats

Stats: Pace, Off/Def Rtg, FGM, FG3M, FTM


### 2. Team style change from 1990 to 2020
### 3. Game style change from 1990 to 2020
### 4. Project record of NBA teams and championship

In [3]:
# import necessary libraries for data analysis and visulization

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

Use nba_api to obtain stats from stats.nba.com 

The nba_api can be accessed through https://github.com/swar/nba_api

Development Version: v1.1.8

MIT License

Copyright (c) 2018 Swar Patel

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

In [99]:
! pip install nba_api

Requirement already satisfied: nba_api in /opt/anaconda3/lib/python3.7/site-packages (1.1.8)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.7/site-packages (from nba_api) (2.22.0)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/anaconda3/lib/python3.7/site-packages (from requests->nba_api) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.7/site-packages (from requests->nba_api) (2019.9.11)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/anaconda3/lib/python3.7/site-packages (from requests->nba_api) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/anaconda3/lib/python3.7/site-packages (from requests->nba_api) (1.24.2)

### Import all 30 NBA teams and store into nba_teams.csv

In [35]:
from nba_api.stats.static import teams

# get_teams returns a list of 30 dictionaries, each an NBA team.
nba_teams = teams.get_teams()
nba_teams = pd.DataFrame(nba_teams)

# Correct 'city' for teams
wrong_city = ['Golden State',  'Minnesota',  'Indiana',     'Utah',          'Washington']
right_city = ['San Francisco', 'Minneapolis','Indianapolis','Salt Lake City','Washington, D.C.']
nba_teams['city'].replace(to_replace=wrong_city, value=right_city, inplace=True)

# Correct 'city' for teams
wrong_state = ['Atlanta']
right_state = ['Georgia']
nba_teams['state'].replace(to_replace=wrong_state, value=right_state, inplace=True)
nba_teams.sort_values(by='full_name', inplace=True)
nba_teams.to_csv('nba_teams.csv')

In [36]:
nba_teams= pd.read_csv('nba_teams.csv')

In [37]:
nba_teams

,Unnamed: 0,id,full_name,abbreviation,nickname,city,state,year_founded
0,0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Georgia,1949
1,1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,14,1610612751,Brooklyn Nets,BKN,Nets,Brooklyn,New York,1976
3,29,1610612766,Charlotte Hornets,CHA,Hornets,Charlotte,North Carolina,1988
4,4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966
5,2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
6,5,1610612742,Dallas Mavericks,DAL,Mavericks,Dallas,Texas,1980
7,6,1610612743,Denver Nuggets,DEN,Nuggets,Denver,Colorado,1976
8,28,1610612765,Detroit Pistons,DET,Pistons,Detroit,Michigan,1948
9,7,1610612744,Golden State Warriors,GSW,Warriors,San Francisco,California,1946
10,8,1610612745,Houston Rockets,HOU,Rockets,Houston,Texas,1967
11,17,1610612754,Indiana Pacers,IND,Pacers,Indianapolis,Indiana,1976
12,9,1610612746,Los Angeles Clippers,LAC,Clippers,Los Angeles,California,1970
13,10,1610612747,Los Angeles Lakers,LAL,Lakers,Los Angeles,California,1948
14,26,1610612763,Memphis Grizzlies,MEM,Grizzlies,Memphis,Tennessee,1995
15,11,1610612748,Miami Heat,MIA,Heat,Miami,Florida,1988
16,12,1610612749,Milwaukee Bucks,MIL,Bucks,Milwaukee,Wisconsin,1968
17,13,1610612750,Minnesota Timberwolves,MIN,Timberwolves,Minneapolis,Minnesota,1989
18,3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
19,15,1610612752,New York Knicks,NYK,Knicks,New York,New York,1946
20,23,1610612760,Oklahoma City Thunder,OKC,Thunder,Oklahoma City,Oklahoma,1967
21,16,1610612753,Orlando Magic,ORL,Magic,Orlando,Florida,1989
22,18,1610612755,Philadelphia 76ers,PHI,76ers,Philadelphia,Pennsylvania,1949
23,19,1610612756,Phoenix Suns,PHX,Suns,Phoenix,Arizona,1968
24,20,1610612757,Portland Trail Blazers,POR,Trail Blazers,Portland,Oregon,1970
25,21,1610612758,Sacramento Kings,SAC,Kings,Sacramento,California,1948
26,22,1610612759,San Antonio Spurs,SAS,Spurs,San Antonio,Texas,1976
27,24,1610612761,Toronto Raptors,TOR,Raptors,Toronto,Ontario,1995
28,25,1610612762,Utah Jazz,UTA,Jazz,Salt Lake City,Utah,1974
29,27,1610612764,Washington Wizards,WAS,Wizards,"Washington, D.C.",District of Columbia,1961

### Import all NBA players (current and retired) and store into  nba_players.csv

In [101]:
from nba_api.stats.static import players
# get_players returns a list of dictionaries, each representing a player.
nba_players = players.get_players()
nba_players = pd.DataFrame(nba_players)
nba_players.to_csv('nba_players.csv')

In [38]:
nba_players = pd.read_csv('nba_players.csv')

In [39]:
nba_players

,Unnamed: 0,id,full_name,first_name,last_name,is_active
0,0,76001,Alaa Abdelnaby,Alaa,Abdelnaby,False
1,1,76002,Zaid Abdul-Aziz,Zaid,Abdul-Aziz,False
2,2,76003,Kareem Abdul-Jabbar,Kareem,Abdul-Jabbar,False
3,3,51,Mahmoud Abdul-Rauf,Mahmoud,Abdul-Rauf,False
4,4,1505,Tariq Abdul-Wahad,Tariq,Abdul-Wahad,False
...,...,...,...,...,...,...
4496,4496,1627790,Ante Zizic,Ante,Zizic,True
4497,4497,78647,Jim Zoet,Jim,Zoet,False
4498,4498,78648,Bill Zopf,Bill,Zopf,False
4499,4499,1627826,Ivica Zubac,Ivica,Zubac,True
4500,4500,78650,Matt Zunic,Matt,Zunic,False

### Import all NBA players (current and retired) draft combine stats (if exist) and store into draft_combine_stats.csv

In [105]:
from nba_api.stats.endpoints import DraftCombineStats

# Important feasures: 
body = ['PLAYER_ID','PLAYER_NAME', 'SEASON', 'HEIGHT_WO_SHOES', 'WEIGHT', 'WINGSPAN', 'STANDING_REACH', \
        'STANDING_VERTICAL_LEAP', 'MAX_VERTICAL_LEAP',\
        'LANE_AGILITY_TIME','THREE_QUARTER_SPRINT', 'BENCH_PRESS']

draft_combine_stats = DraftCombineStats(season_all_time='All Time').get_data_frames()[0]
draft_combine_stats = draft_combine_stats[body]
draft_combine_stats.to_csv('draft_combine_stats.csv')

In [41]:
draft_combine_stats = pd.read_csv('draft_combine_stats.csv')

In [42]:
draft_combine_stats

,Unnamed: 0,PLAYER_ID,PLAYER_NAME,SEASON,HEIGHT_WO_SHOES,WEIGHT,WINGSPAN,STANDING_REACH,STANDING_VERTICAL_LEAP,MAX_VERTICAL_LEAP,LANE_AGILITY_TIME,THREE_QUARTER_SPRINT,BENCH_PRESS
0,0,2403,Nene,2002,81.25,253.0,88.50,109.00,30.0,34.0,10.73,3.19,16.0
1,1,12204,Mohamed Abukar,2007,80.00,210.0,81.00,103.00,30.5,35.0,11.78,3.37,15.0
2,2,101165,Alex Acker,2005,75.75,183.0,84.00,102.50,28.0,32.0,11.67,3.35,11.0
3,3,203112,Quincy Acy,2012,78.50,223.8,86.75,106.50,32.0,37.0,10.48,3.28,13.0
4,4,203500,Steven Adams,2013,82.75,254.5,88.50,109.50,28.5,33.0,11.85,3.40,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,1345,1962937123,Omer Yurtseven,2017,82.50,248.4,85.00,108.50,26.0,31.5,12.85,3.45,6.0
1346,1346,203092,Tyler Zeller,2012,83.25,247.4,84.00,104.50,30.0,34.0,11.13,3.40,16.0
1347,1347,203469,Cody Zeller,2013,82.75,230.0,82.75,106.00,35.5,37.5,10.82,3.15,17.0
1348,1348,2583,Derrick Zimmerman,2003,73.00,190.0,81.00,96.25,34.0,40.5,11.09,3.10,13.0
1349,1349,1627757,Stephen Zimmerman,2016,82.25,234.0,87.25,108.50,26.0,31.0,12.08,3.43,NaN

### Merge nba_player and draft_combine_stats, select active players as nba_players_active

Only use important features:  

'HEIGHT_WO_SHOES', 'WEIGHT', 'WINGSPAN', 'STANDING_REACH', 

'STANDING_VERTICAL_LEAP', 'MAX_VERTICAL_LEAP', 'LANE_AGILITY_TIME', 'THREE_QUARTER_SPRINT', 'BENCH_PRESS'

In [ ]:
nba_players_draft_combine_stats = pd.merge(nba_players, draft_combine_stats, left_on='id', right_on='PLAYER_ID', how='left')
nba_players_draft_combine_stats.drop(['PLAYER_ID','PLAYER_NAME'],1,inplace=True)

nba_players_active = nba_players_draft_combine_stats[ nba_players_draft_combine_stats['is_active']==True ]

### Import all NBA team stats (gamelogs), Season 2019-20

In [ ]:
from nba_api.stats.endpoints import teamgamelogs

# seanson_range = list(range(2020,2009,-1))
season = '2019-20'
season_type = 'Regular Season'
team_id_all = nba_teams['id']
allteam_gamelog_2019_20 = pd.DataFrame()

for team_id in team_id_all:
    teamgamelogs_finder = teamgamelogs.TeamGameLogs(season_nullable=season, season_type_nullable=season_type, team_id_nullable=team_id)
    gamelog_2019_20 = teamgamelogs_finder.team_game_logs.get_data_frame()
    allteam_gamelog_2019_20 = allteam_gamelog_2019_20.append(gamelog_2019_20)
    
# utah_gamelog_2019_20.to_csv('utah_gamelog_2019_20.csv')

features = 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA',\
           'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'

In [ ]:
allteam_gamelog_2019_20.to_csv('allteam_gamelog_2019_20.csv')

In [43]:
allteam_gamelog_2019_20 = pd.read_csv('allteam_gamelog_2019_20.csv',converters={'GAME_ID': str})

In [50]:
allteam_gamelog_2019_20.head(1)

,Unnamed: 0,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,0,2019-20,1610612737,ATL,Atlanta Hawks,0021900821,2020-02-20T00:00:00,ATL vs. MIA,W,48.0,...,33,33,25,23,17,33,43,1,3,11

### Import all NBA team avanced boxscore stats, Season 2019-20

In [ ]:
allteam_game_id_2019_20 = allteam_gamelog_2019_20['GAME_ID'].unique()

allteam_adv_box_team = pd.DataFrame()

for game_id in allteam_game_id_2019_20:
    boxscoreadvanced_finder = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id=game_id)
    boxscore_advanced_team = boxscoreadvanced_finder.team_stats.get_data_frame()
    allteam_adv_box_team = allteam_adv_box_team.append(boxscore_advanced_team)    

allteam_adv_box_team.shape

In [ ]:
allteam_adv_box_team.to_csv('allteam_adv_box_team_2019_20.csv')

In [44]:
allteam_adv_box_team = pd.read_csv('allteam_adv_box_team_2019_20.csv')

### Import all NBA team scoring boxscore stats, Season 2019-20

In [20]:
from nba_api.stats.endpoints import boxscorescoringv2
 
allteam_game_id_2019_20 = allteam_gamelog_2019_20['GAME_ID'].unique()

allteam_scoring_box_team = pd.DataFrame()

for game_id in allteam_game_id_2019_20:
    boxscorescoring_finder = boxscorescoringv2.BoxScoreScoringV2(game_id=game_id)
    boxscore_scoring_team = boxscorescoring_finder.sql_teams_scoring.get_data_frame()
    allteam_scoring_box_team = allteam_scoring_box_team.append(boxscore_scoring_team)

In [21]:
allteam_scoring_box_team.to_csv('allteam_scoring_box_team_2019_20.csv')

In [27]:
allteam_scoring_box_team = pd.read_csv('allteam_scoring_box_team_2019_20.csv',converters={'GAME_ID': str})
allteam_scoring_box_team.head()

,Unnamed: 0,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,PCT_FGA_2PT,PCT_FGA_3PT,PCT_PTS_2PT,...,PCT_PTS_FB,PCT_PTS_FT,PCT_PTS_OFF_TOV,PCT_PTS_PAINT,PCT_AST_2PM,PCT_UAST_2PM,PCT_AST_3PM,PCT_UAST_3PM,PCT_AST_FGM,PCT_UAST_FGM
0,0,0021900821,1610612748,Heat,MIA,Miami,240:00,0.622,0.378,0.468,...,0.129,0.266,0.161,0.387,0.586,0.414,1.000,0.000,0.700,0.300
1,1,0021900821,1610612737,Hawks,ATL,Atlanta,240:00,0.588,0.412,0.388,...,0.085,0.240,0.155,0.357,0.520,0.480,0.563,0.438,0.537,0.463
2,0,0021900807,1610612739,Cavaliers,CLE,Cleveland,240:00,0.702,0.298,0.598,...,0.079,0.165,0.189,0.535,0.421,0.579,0.900,0.100,0.521,0.479
3,1,0021900807,1610612737,Hawks,ATL,Atlanta,240:00,0.595,0.405,0.438,...,0.114,0.190,0.190,0.419,0.565,0.435,0.846,0.154,0.667,0.333
4,0,0021900795,1610612753,Magic,ORL,Orlando,240:00,0.600,0.400,0.474,...,0.126,0.126,0.133,0.444,0.469,0.531,1.000,0.000,0.660,0.340

### Import all NBA team defensive boxscore stats, Season 2019-20

In [ ]:
from nba_api.stats.endpoints import boxscoredefensive

allteam_game_id_2019_20 = allteam_gamelog_2019_20['GAME_ID'].unique()

allteam_defensive_box_team = pd.DataFrame()

for game_id in allteam_game_id_2019_20:
    boxscoredefensive_finder = boxscoredefensive.BoxScoreDefensive(game_id=game_id, timeout=100)
    boxscore_defensive_team = boxscoredefensive_finder.player_defensive_stats.get_data_frame()
    allteam_defensive_box_team = allteam_defensive_box_team.append(boxscore_defensive_team)  

allteam_defensive_box_team.shape()

In [ ]:
from nba_api.stats.endpoints import defensehub

defensehub_finder = defensehub.DefenseHub(game_scope_detailed='Season',league_id='00',player_or_team='Team',player_scope='All Players',season='2019-20',season_type_playoffs='Regular Season')
team_defense_hub = teamdefend_finder.defense_hub_stat1.get_data_frame()

team_defense_hub

In [65]:
from nba_api.stats.endpoints import leaguedashptteamdefend

teamdefend_finder = leaguedashptteamdefend.LeagueDashPtTeamDefend(defense_category='Overall',league_id='00',per_mode_simple='PerGame',season='2019-20')
team_defend = teamdefend_finder.league_dash_pt_team_defend.get_data_frame()

team_defend

,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,GP,G,FREQ,D_FGM,D_FGA,D_FG_PCT,NORMAL_FG_PCT,PCT_PLUSMINUS
0,1610612749,Milwaukee Bucks,MIL,55,55,1.0,38.44,93.56,0.411,0.452,-0.041
1,1610612761,Toronto Raptors,TOR,57,57,1.0,37.58,87.98,0.427,0.453,-0.026
2,1610612746,LA Clippers,LAC,56,56,1.0,39.41,90.16,0.437,0.460,-0.023
3,1610612751,Brooklyn Nets,BKN,55,55,1.0,40.76,92.89,0.439,0.456,-0.017
4,1610612738,Boston Celtics,BOS,56,56,1.0,37.95,86.00,0.441,0.456,-0.014
5,1610612747,Los Angeles Lakers,LAL,55,55,1.0,38.98,87.35,0.446,0.459,-0.013
6,1610612757,Portland Trail Blazers,POR,57,57,1.0,41.58,91.98,0.452,0.462,-0.010
7,1610612754,Indiana Pacers,IND,57,57,1.0,39.26,87.46,0.449,0.458,-0.009
8,1610612743,Denver Nuggets,DEN,57,57,1.0,39.23,85.98,0.456,0.464,-0.008
9,1610612748,Miami Heat,MIA,55,55,1.0,38.69,86.65,0.446,0.455,-0.008
10,1610612755,Philadelphia 76ers,PHI,57,57,1.0,39.00,85.60,0.456,0.463,-0.007
11,1610612760,Oklahoma City Thunder,OKC,57,57,1.0,40.60,89.32,0.455,0.461,-0.006
12,1610612763,Memphis Grizzlies,MEM,56,56,1.0,41.00,90.27,0.454,0.458,-0.004
13,1610612742,Dallas Mavericks,DAL,56,56,1.0,41.30,91.11,0.453,0.457,-0.004
14,1610612762,Utah Jazz,UTA,56,56,1.0,40.11,89.21,0.450,0.454,-0.004
15,1610612753,Orlando Magic,ORL,56,56,1.0,39.36,85.80,0.459,0.462,-0.003
16,1610612745,Houston Rockets,HOU,56,56,1.0,42.34,91.61,0.462,0.459,0.004
17,1610612752,New York Knicks,NYK,56,56,1.0,39.66,85.48,0.464,0.458,0.006
18,1610612740,New Orleans Pelicans,NOP,57,57,1.0,42.75,91.86,0.465,0.459,0.006
19,1610612759,San Antonio Spurs,SAS,55,55,1.0,42.11,89.62,0.470,0.463,0.007
20,1610612758,Sacramento Kings,SAC,56,56,1.0,39.70,84.96,0.467,0.458,0.009
21,1610612741,Chicago Bulls,CHI,58,58,1.0,39.33,82.81,0.475,0.463,0.012
22,1610612750,Minnesota Timberwolves,MIN,55,55,1.0,42.36,89.95,0.471,0.459,0.012
23,1610612765,Detroit Pistons,DET,58,58,1.0,41.83,87.91,0.476,0.462,0.013
24,1610612744,Golden State Warriors,GSW,57,57,1.0,42.00,88.46,0.475,0.459,0.015
25,1610612766,Charlotte Hornets,CHA,55,55,1.0,41.51,87.49,0.474,0.458,0.016
26,1610612756,Phoenix Suns,PHX,56,56,1.0,41.32,87.07,0.475,0.458,0.016
27,1610612737,Atlanta Hawks,ATL,58,58,1.0,43.02,90.41,0.476,0.458,0.018
28,1610612764,Washington Wizards,WAS,55,55,1.0,43.07,88.65,0.486,0.456,0.030
29,1610612739,Cleveland Cavaliers,CLE,56,56,1.0,43.82,89.14,0.492,0.457,0.034

In [ ]:
allteam_defensive_box_team.to_csv('allteam_defensive_box_team_2019_20.csv')

In [ ]:
allteam_defensive_box_team = pd.read_csv('allteam_defensive_box_team_2019_20.csv')

### Merge all NBA team traditional and advanced box score Season 2019-20, drop repeated feasutres, keep import features

In [ ]:
allteam_overall_box_2019_20 = pd.merge(allteam_gamelog_2019_20, allteam_adv_box_team, \
                                       left_on=['GAME_ID', 'TEAM_ID', 'TEAM_ABBREVIATION'],\
                                       right_on=['GAME_ID', 'TEAM_ID', 'TEAM_ABBREVIATION'],how='inner')

features = ['SEASON_YEAR', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME_x', \
           'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'MIN_x', \
           'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT',\
           'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'PF', 'PTS', 'PLUS_MINUS',\
            'E_OFF_RATING', 'OFF_RATING', 'E_DEF_RATING', 'DEF_RATING', 'E_NET_RATING', 'NET_RATING', \
            'AST_PCT', 'AST_TOV', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', \
            'E_TM_TOV_PCT', 'TM_TOV_PCT', 'EFG_PCT', 'TS_PCT', 'USG_PCT', 'E_USG_PCT', \
            'E_PACE', 'PACE', 'PACE_PER40', 'POSS', 'PIE']

allteam_overall_box_2019_20 = allteam_overall_box_2019_20[features]
allteam_overall_box_2019_20.to_csv('allteam_overall_box_2019_20.csv')

In [ ]:
allteam_overall_box_2019_20 = pd.read_csv('allteam_overall_box_2019_20.csv')

In [ ]:
sns.scatterplot(x='PACE', y='DEF_RATING', data=utah_overall_box_2019_20)

In [ ]:
features = ['FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT',\
            'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'PF', 'PTS', 'PLUS_MINUS',\
            'OFF_RATING', 'DEF_RATING', 'NET_RATING', \
            'AST_PCT', 'AST_TOV', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', \
            'TM_TOV_PCT', 'EFG_PCT', 'TS_PCT', \
            'PACE', 'PACE_PER40', 'POSS', 'PIE']
test = utah_overall_box_2019_20[features]

# fig1,ax1 = plt.subplots(figsize=(15,15))
# Heatmap of correlation efficients between features
# ax1 = sns.heatmap(test.corr(), vmin=-1, vmax=1, center= 0, cmap= 'coolwarm')

# Pairplot of of different features
sns.pairplot(test, vars=['PTS', 'FGA', 'FG3A'], kind='reg')

In [ ]:
test = allteam_overall_box_2019_20.groupby('TEAM_NAME_x').mean()

# sns.scatterplot(x='PACE', y='FGA', data=test)
sns.pairplot(test, vars=['PTS', 'FGA', 'FG3A'], kind='reg')

### Import player awards

In [106]:
from nba_api.stats.endpoints import playerawards

# Find player_id
player_id = nba_players[nba_players['full_name']=='Karl Malone']['id']

playerawards_finder = playerawards.PlayerAwards(player_id=player_id)

player_awards = playerawards_finder.player_awards.get_data_frame()

### Import draft history

In [53]:
from nba_api.stats.endpoints import drafthistory

drafthistory_finder = drafthistory.DraftHistory(league_id='00')

draft_history = drafthistory_finder.draft_history.get_data_frame()
draft_history.to_csv('NBA_draft_history.csv')

In [54]:
draft_history = pd.read_csv('NBA_draft_history.csv')

### Import Utah Jazz team roster and store into a df utah_roster

In [104]:
from nba_api.stats.endpoints import commonteamroster
utah_id = 1610612762
roster_finder = commonteamroster.CommonTeamRoster(season = '2019-20', team_id=utah_id)
utah_roster = roster_finder.common_team_roster.get_data_frame()

### Import Utah Jazz team stats, Season 2019-20

In [110]:
from nba_api.stats.endpoints import teamgamelogs

# seanson_range = list(range(2020,2009,-1))
season = '2019-20'
season_type = 'Regular Season'

teamgamelogs_finder = teamgamelogs.TeamGameLogs(season_nullable=season, season_type_nullable=season_type, team_id_nullable=utah_id)
utah_gamelog_2019_20 = teamgamelogs_finder.team_game_logs.get_data_frame()

utah_gamelog_2019_20.to_csv('utah_gamelog_2019_20.csv')

features = 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA',\
           'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'

### Import Utah Jazz player boxscore stats, Season 2019-20

In [ ]:
from nba_api.stats.endpoints import boxscoretraditionalv2

utah_game_id_2019_20 = utah_gamelog_2019_20['GAME_ID']
utah_box_players = pd.DataFrame()

for game_id in utah_game_id_2019_20:
    boxscoretraditional_finder = boxscoretraditionalv2.BoxScoreTraditionalV2(game_id=game_id)
    boxscore = boxscoretraditional_finder.player_stats.get_data_frame()
    utah_box_players = utah_box_players.append(boxscore[boxscore.TEAM_ID==utah_id])

In [ ]:
utah_box_players.to_csv('utah_box_players_2019_20.csv')

In [ ]:
utah_box_players = pd.read_csv('utah_box_players_2019_20.csv')

### Import Utah Jazz players avanced boxscore stats, Season 2019-20

In [ ]:
from nba_api.stats.endpoints import boxscoreadvancedv2

utah_game_id_2019_20 = utah_gamelog_2019_20['GAME_ID']
utah_adv_box_players = pd.DataFrame()

for game_id in utah_game_id_2019_20:
    boxscoreadvanced_finder = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id=game_id)
    boxscore_advanced = boxscoreadvanced_finder.player_stats.get_data_frame()
    utah_adv_box_players = utah_adv_box_players.append(boxscore_advanced[boxscore_advanced.TEAM_ID==utah_id])

In [ ]:
utah_adv_box_players.to_csv('utah_adv_box_players_2019_20.csv')

In [ ]:
utah_adv_box_players = pd.read_csv('utah_adv_box_players_2019_20.csv')

### Import Utah Jazz team avanced boxscore stats, Season 2019-20

In [ ]:
utah_adv_box_team = pd.DataFrame()

for game_id in utah_game_id_2019_20:
    boxscoreadvanced_finder = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id=game_id)
    boxscore_advanced_team = boxscoreadvanced_finder.team_stats.get_data_frame()
    utah_adv_box_team = utah_adv_box_team.append(boxscore_advanced_team[boxscore_advanced_team.TEAM_ID==utah_id])    

utah_adv_box_team

In [ ]:
utah_adv_box_team.to_csv('utah_adv_box_team_2019_20.csv')

In [ ]:
utah_adv_box_team = pd.read_csv('utah_adv_box_team_2019_20.csv')

### Merge Utah Jazz team traditional and advanced box score Season 2019-20, drop repeated feasutres, keep import features

In [ ]:
utah_overall_box_2019_20 = pd.merge(utah_box_team_2019_20, utah_adv_box_team_2019_20, on='GAME_ID', how='left')

features = ['SEASON_YEAR', 'TEAM_ID_x', 'TEAM_ABBREVIATION_x', 'TEAM_NAME_x', \
           'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'MIN_x', \
           'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT',\
           'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'PF', 'PTS', 'PLUS_MINUS',\
            'E_OFF_RATING', 'OFF_RATING', 'E_DEF_RATING', 'DEF_RATING', 'E_NET_RATING', 'NET_RATING', \
            'AST_PCT', 'AST_TOV', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', \
            'E_TM_TOV_PCT', 'TM_TOV_PCT', 'EFG_PCT', 'TS_PCT', 'USG_PCT', 'E_USG_PCT', \
            'E_PACE', 'PACE', 'PACE_PER40', 'POSS', 'PIE']

utah_overall_box_2019_20 = utah_overall_box_2019_20[features]
# utah_overall_box_2019_20.to_csv('utah_overall_box_2019_20.csv')